import tkinter
from tkinter import Tk, Label, Entry, Menu
main_window = tkinter.Tk(screenName="Main Window", className="Default")
main_window.title('Hopeful')
Label(main_window, text='UserName').grid(row=0) 
Label(main_window, text='Password').grid(row=1)
e1 = Entry(main_window)
e2 = Entry(main_window, show="*")
e1.grid(row=0, column=1) 
e2.grid(row=1, column=1) 
menu = Menu(main_window)  
main_window.config(menu=menu) 
filemenu = Menu(menu)
menu.add_cascade(label='File', menu=filemenu)
filemenu.add_command(label='Exit', command=main_window.quit)
helpmenu = Menu(menu) 
menu.add_cascade(label='Help', menu=helpmenu)
helpmenu.add_command(label='About') 
main_window.mainloop()